stages:
  - test

include:
    - project: Northern.tech/Mender/mendertesting
      file:
        - .gitlab-ci-github-status-updates.yml
        - .gitlab-ci-check-license.yml
    - component: gitlab.com/Northern.tech/Mender/mendertesting/commit-lint@master
