#!/bin/sh
# Copyright 2024 Northern.tech AS
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

set -e

STATE="$1"
FILES="$2"
COMPONENT_TYPE="$3"
COMPONENT_ID="$4"

case "$STATE" in
    NeedsArtifactReboot)
        echo "Automatic"
        ;;
    NeedsUnpackedArtifact)
        echo "No"
        ;;
    SupportsRollback)
        echo "Yes"
        ;;

    Download)
        name="$(cat $FILES/stream-next)"
        # There is no stopping after Download_Error. The download stage is not supposed to have any
        # side effects, so if the download fails, everything is immediately rolled back and cleaned
        # up. Remaining states below will just return "no update in progress", which we handle.
        mender-update install --stop-after Download_Leave "$FILES/$name"
        test -z "$(cat $FILES/stream-next)"
        ;;

    ArtifactInstall)
        mender-update resume --stop-after ArtifactInstall_Leave --stop-after ArtifactInstall_Error
        ;;

    ArtifactRollback)
        ret=0
        mender-update rollback --stop-after ArtifactRollback_Leave || ret=$?
        if [ $ret -eq 2 ]; then
            # Return code 2 means there is no update in progress, which means that the rollback
            # already completed.
            exit 0
        else
            exit $ret
        fi
        ;;

    ArtifactFailure)
        ret=0
        mender-update resume --stop-after ArtifactFailure_Leave || ret=$?
        if [ $ret -eq 2 ]; then
            # Return code 2 means there is no update in progress, which means that the rollback
            # already completed.
            exit 0
        else
            exit $ret
        fi
        ;;

    ArtifactCommit)
        # Stopping after ArtifactCommit is important in order to prevent Cleanup from being
        # run. This enables us to still roll back.
        mender-update commit --stop-after ArtifactCommit --stop-after ArtifactCommit_Error
        ;;

    Cleanup)
        # Finish up cleanup. Note that this may also run ArtifactCommit_Leave scripts.
        ret=0
        mender-update resume || ret=$?
        if [ $ret -eq 2 ]; then
            # Return code 2 means there is no update in progress, which means that the rollback
            # already completed.
            exit 0
        else
            exit $ret
        fi
        ;;

    Provides)
        mender-update show-provides
        # Also submit device_type, which is in a separate file, not in the database. We don't know if the
        # file contains a newline, so it's important that this is done last, to avoid corrupting other
        # entries.
        grep '^device_type=' ${MENDER_DATASTORE_DIR:-/var/lib/mender}/device_type
        ;;

    Inventory)
        mender-update show-inventory
        ;;

esac
